const ACCESS_TOKEN_LIFETIME = 600; // 10 minutes
const REFRESH_TOKEN_LIFETIME = 604800; // 1 week
const ACTIVATION_CODE_LIFETIME = 86400; // 1 day

module.exports = {
  ACCESS_TOKEN_LIFETIME,
  REFRESH_TOKEN_LIFETIME,
  ACTIVATION_CODE_LIFETIME,
};
